import urllib.request
import json
import os
import datetime
import time

URL = "https://paruluniversity.ac.in/"
WEBHOOK_URL = os.getenv("DISCORD_WEBHOOK") 

def send_discord_alert(message):
    if not WEBHOOK_URL:
        return
    data = {"content": message}
    headers = {
        "Content-Type": "application/json",
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"
    }
    req = urllib.request.Request(WEBHOOK_URL, json.dumps(data).encode(), headers)
    try:
        urllib.request.urlopen(req)
    except Exception as e:
        print(f"Alert failed: {e}")

def check_site():
    start_time = time.time()
    try:
        code = urllib.request.urlopen(URL, timeout=10).getcode()
        latency = round((time.time() - start_time) * 1000) 
        if code == 200:
            return "🟢 UP", latency
        else:
            return f"🟡 WARNING ({code})", latency
    except Exception as e:
        return "🔴 DOWN", 0

def generate_html_dashboard():
    # Read the last 10 lines of the log
    try:
        with open("status_log.txt", "r") as f:
            logs = f.readlines()[-10:]
    except:
        logs = ["No data yet."]
        
    # Create a sleek, dark-mode HTML page
    html_content = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <title>DevOps Status Dashboard</title>
        <style>
            body {{ background-color: #0d1117; color: #c9d1d9; font-family: monospace; padding: 40px; text-align: center; }}
            h1 {{ color: #58a6ff; }}
            .log-box {{ background: #161b22; padding: 20px; border-radius: 10px; border: 1px solid #30363d; display: inline-block; text-align: left; line-height: 1.8; }}
            .footer {{ margin-top: 30px; font-size: 12px; color: #8b949e; }}
        </style>
    </head>
    <body>
        <h1>🫀 Serverless Uptime Dashboard</h1>
        <p>Live monitoring for: <b>{URL}</b></p>
        <div class="log-box">
            {"<br>".join(logs)}
        </div>
        <div class="footer">Auto-generated by GitHub Actions CI/CD Pipeline</div>
    </body>
    </html>
    """
    with open("index.html", "w") as f:
        f.write(html_content)

if __name__ == "__main__":
    status, latency = check_site()
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    log_entry = f"{timestamp} | {URL} | Status: {status} | Latency: {latency}ms\n"
    
    with open("status_log.txt", "a") as file:
        file.write(log_entry)
        
    # Trigger the Discord alert if things are bad
    if "DOWN" in status or "WARNING" in status or latency > 1000:
        alert_msg = f"🚨 **MONITOR ALARM** 🚨\n**Target:** {URL}\n**Status:** {status}\n**Latency:** {latency}ms"
        send_discord_alert(alert_msg)
        
    # Generate the shiny new webpage!
    generate_html_dashboard()
        
        if code == 200:
            return "🟢 UP", latency
        else:
            return f"🟡 WARNING ({code})", latency
    except Exception as e:
        return "🔴 DOWN", 0

if __name__ == "__main__":
    status, latency = check_site()
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    log_entry = f"{timestamp} | {URL} | Status: {status} | Latency: {latency}ms\n"
    
    with open("status_log.txt", "a") as file:
        file.write(log_entry)
        
    print(f"Logged: {log_entry}")

    # The Alert Trigger: Only ping Discord if it's down, warning, or dangerously slow (> 1000ms)
    if "DOWN" in status or "WARNING" in status or latency > 1000:
        alert_msg = f"🚨 **MONITOR ALARM** 🚨\n**Target:** {URL}\n**Status:** {status}\n**Latency:** {latency}ms"
        send_discord_alert(alert_msg)
